name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - build/**
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install
        run: npm i

      - name: Build website
        run: npm run build

      - name: Touch nojekyll
        run: touch build/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
          # Remove previous build files
          clean: true
          # Do not remove the `.nojekyll` file: we have manually added an empty `.nojekyll` file at the root of the `gh-pages` branch and we don't want having to re-create it after each build.
          clean-exclude: |
            .nojekyll
